# Use postgres/example user/password credentials
version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  dynamodb:
    container_name: dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    volumes:
      - "./.artifacts/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  # api-server-express:
  #   container_name: api-server-express
  #   build: ./aws_sam_app/server_nodejs/Dockerfile.api-server-express
