import {
  DndContext,
  DragEndEvent,
  KeyboardSensor,
  PointerSensor,
  closestCenter,
  useSensor,
  useSensors,
} from '@dnd-kit/core';
import {
  SortableContext,
  sortableKeyboardCoordinates,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable';
import styled from '@emotion/styled';
import { A } from '@mobily/ts-belt';
import { useCallback } from 'react';
import { SubmitHandler, useFieldArray, useForm } from 'react-hook-form';
import { useNodeId, useUpdateNodeInternals } from 'reactflow';
import invariant from 'tiny-invariant';

import { ConnectorID, NodeID } from 'flow-models';

import { useFlowStore } from 'state-flow/context/FlowStoreContext';

import NodeBoxVariableEditableItem from './NodeBoxVariableEditableItem';
import { FormValue, VariableConfig } from './types';

type Props = {
  variables: VariableConfig[];
  isSortable?: boolean;
  onRowHeightChange?: (index: number, height: number) => void;
};

function NodeBoxVariablesEditableList(props: Props) {
  const nodeId = useNodeId() as NodeID;
  const updateNodeInternals = useUpdateNodeInternals();

  const updateVariable = useFlowStore((s) => s.updateVariable);
  const removeVariable = useFlowStore((s) => s.removeVariable);

  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    }),
  );

  const { control, handleSubmit } = useForm<FormValue>({
    values: {
      variables: props.variables,
    },
  });

  // NOTE: field will contain all properties of the variable except
  // the "id" is generated by react-hook-form.
  // But in SubmitHandler, the "id" will be the id from the original
  // variable object.
  const { fields, remove, move } = useFieldArray({
    control,
    name: 'variables',
  });

  const updateVariables = useCallback<SubmitHandler<FormValue>>(
    (data) => {
      // NOTE: We don't handle add variable here

      if (props.variables.length === data.variables.length) {
        // This is an update

        // NOTE: Elements from the first array, not existing in the
        // second array.
        const updatedVariables = A.difference(data.variables, props.variables);

        for (const changedVariable of updatedVariables) {
          invariant(
            !changedVariable.isReadOnly,
            'Variable should not be readonly',
          );
          updateVariable(changedVariable.id as ConnectorID, {
            name: changedVariable.name,
          });
        }
      } else {
        // This is a remove

        // NOTE: Elements from the first array, not existing in the
        // second array. Note the order of the arguments is different from
        // above.
        const removedVariables = A.difference(props.variables, data.variables);

        for (const removedVariable of removedVariables) {
          invariant(
            !removedVariable.isReadOnly,
            'Variable should not be readonly',
          );
          removeVariable(removedVariable.id as ConnectorID);
        }

        // NOTE: Removing a variable will affect edge and handle positions.
        updateNodeInternals(nodeId);
      }
    },
    [
      props.variables,
      nodeId,
      removeVariable,
      updateNodeInternals,
      updateVariable,
    ],
  );

  const onDragEnd = useCallback(
    (event: DragEndEvent) => {
      const { active, over } = event;

      if (over == null || active.id === over.id) {
        return;
      }

      const oldIndex = fields.findIndex((f) => f.id === active.id);
      const newIndex = fields.findIndex((f) => f.id === over.id);

      move(oldIndex, newIndex);

      handleSubmit((data) => {
        updateVariable(data.variables[oldIndex].id as ConnectorID, {
          // Which index to use for which variable is not important here
          // since data will contain variables in updated order.
          index: oldIndex,
        });
        updateVariable(data.variables[newIndex].id as ConnectorID, {
          index: newIndex,
        });

        // NOTE: Removing a variable will affect edge and handle positions.
        updateNodeInternals(nodeId);
      })();
    },
    [nodeId, fields, handleSubmit, move, updateNodeInternals, updateVariable],
  );

  let editableItemStart = fields.findIndex((f) => !f.isReadOnly);
  if (editableItemStart === -1) {
    editableItemStart = fields.length;
  }

  return (
    <Container>
      <div>
        {fields.slice(0, editableItemStart).map((field, index) => {
          // TODO: Find a way to avoid duplicating the mapper
          const variable = props.variables[index];
          return (
            <NodeBoxVariableEditableItem
              key={field.id}
              isReadOnly={variable.isReadOnly}
              isSortable={false}
              control={control}
              field={field}
              index={index}
              helperText={variable.helperMessage}
              onConfirmNameChange={() => {
                handleSubmit(updateVariables)();
              }}
              onRemove={() => {
                remove(index);
                handleSubmit(updateVariables)();
              }}
              onHeightChange={(height) => {
                props.onRowHeightChange?.(index, height);
              }}
            />
          );
        })}
      </div>
      <DndContext
        sensors={sensors}
        collisionDetection={closestCenter}
        onDragEnd={onDragEnd}
      >
        <SortableContext
          disabled={!props.isSortable}
          items={fields}
          strategy={verticalListSortingStrategy}
        >
          <div>
            {fields.slice(editableItemStart).map((field, index) => {
              index += editableItemStart;
              const variable = props.variables[index];

              if (variable == null) {
                return null;
              }

              return (
                <NodeBoxVariableEditableItem
                  key={field.id}
                  isReadOnly={variable.isReadOnly}
                  isSortable={!!props.isSortable}
                  control={control}
                  field={field}
                  index={index}
                  helperText={variable.helperMessage}
                  onConfirmNameChange={() => {
                    handleSubmit(updateVariables)();
                  }}
                  onRemove={() => {
                    remove(index);
                    handleSubmit(updateVariables)();
                  }}
                  onHeightChange={(height) => {
                    props.onRowHeightChange?.(index, height);
                  }}
                />
              );
            })}
          </div>
        </SortableContext>
      </DndContext>
    </Container>
  );
}

const Container = styled.div`
  position: relative;
  // padding-left: 10px;
  // padding-right: 10px;
  margin-bottom: 10px;
`;

export default NodeBoxVariablesEditableList;
