"""Add flow_content field to space

Revision ID: 18f8df59fe46
Revises: f189f5cf0307
Create Date: 2023-09-04 12:14:52.179779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18f8df59fe46'
down_revision: Union[str, None] = 'f189f5cf0307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaces', sa.Column('flow_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaces', 'flow_content')
    # ### end Alembic commands ###
