"""Add content_version column to spaces

Revision ID: c50c0fa59555
Revises: 18f8df59fe46
Create Date: 2023-09-10 14:38:15.333412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50c0fa59555'
down_revision: Union[str, None] = '18f8df59fe46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaces', sa.Column('content_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaces', 'content_version')
    # ### end Alembic commands ###
