AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Promptplay backend using serverless resources.

Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: true
    # Setting this prevent the creation of "Stage" stage in AWS::Serverless::Api
    OpenApiVersion: "2.0"

Resources:
  # --- APIs ---
  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1

  ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64
      Events:
        GetHello:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApi
            Method: GET
            Path: /hello
    Metadata:
      DockerContext: ./server_nodejs
      Dockerfile: Dockerfile
      DockerTag: v1

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessApi}.execute-api.${AWS::Region}.amazonaws.com/v1/hello"
