AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Promptplay backend using serverless resources.

Parameters:
  ApiSubDomainName:
    Type: String
  # NOTE: The HostedZoneId is managed outside of this stack.
  HostedZoneId:
    Type: String
  # SECTION: Environment variables for lambda
  # SECTION: Tables are managed outside of this stack.
  DynamodbTableNameUsers:
    Type: String
  DynamodbTableNamePlaceholderUsers:
    Type: String
  DynamodbTableNameSpaces:
    Type: String
  DynamodbTableNameCsvEvaluationPresets:
    Type: String
  # !SECTION
  Auth0Domain:
    Type: String
  Auth0ClientId:
    Type: String
  Auth0ClientSecret:
    Type: String
  AuthCallbackUrl:
    Type: String
  AuthLoginFinishRedirectUrl:
    Type: String
  AuthLogoutFinishRedirectUrl:
    Type: String
  SessionCookieSecret:
    Type: String
  # !SECTION

Globals:
  Function:
    Timeout: 5
    Tracing: Active
  Api:
    TracingEnabled: true
    # Setting this prevent the creation of "Stage" stage in AWS::Serverless::Api
    OpenApiVersion: "2.0"

Resources:
  # ANCHOR: Cert for *.promptplay.xyz

  CertificateSubDomains:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "*.promptplay.xyz"
      DomainValidationOptions:
        - DomainName: "*.promptplay.xyz"
          # The HostedZone is managed manually on AWS console to prevent
          # catastrophic errors in automation.
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  # ANCHOR: APIs

  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default
      Domain:
        DomainName: !Sub ${ApiSubDomainName}.promptplay.xyz
        CertificateArn: !Ref CertificateSubDomains
        Route53:
          HostedZoneId: !Ref HostedZoneId

  # ANCHOR: Lambda

  ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64
      Events:
        AllTraffic:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApi
            Method: ANY
            Path: /{proxy+}
      Policies:
        # ANCHOR: Users
        - DynamoDBReadPolicy:
            TableName: !Ref DynamodbTableNameUsers
        - DynamoDBWritePolicy:
            TableName: !Ref DynamodbTableNameUsers
        # ANCHOR: Placeholder Users
        - DynamoDBReadPolicy:
            TableName: !Ref DynamodbTableNamePlaceholderUsers
        - DynamoDBWritePolicy:
            TableName: !Ref DynamodbTableNamePlaceholderUsers
        # ANCHOR: Spaces
        - DynamoDBReadPolicy:
            TableName: !Ref DynamodbTableNameSpaces
        - DynamoDBWritePolicy:
            TableName: !Ref DynamodbTableNameSpaces
        # ANCHOR: CsvEvaluationPresets
        - DynamoDBReadPolicy:
            TableName: !Ref DynamodbTableNameCsvEvaluationPresets
        - DynamoDBWritePolicy:
            TableName: !Ref DynamodbTableNameCsvEvaluationPresets
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME_USERS: !Ref DynamodbTableNameUsers
          DYNAMODB_TABLE_NAME_PLACEHOLDER_USERS: !Ref DynamodbTableNamePlaceholderUsers
          DYNAMODB_TABLE_NAME_SPACES: !Ref DynamodbTableNameSpaces
          DYNAMODB_TABLE_NAME_CSV_EVALUATION_PRESETS: !Ref DynamodbTableNameCsvEvaluationPresets
          AUTH0_DOMAIN: !Ref Auth0Domain
          AUTH0_CLIENT_ID: !Ref Auth0ClientId
          AUTH0_CLIENT_SECRET: !Ref Auth0ClientSecret
          AUTH_CALLBACK_URL: !Ref AuthCallbackUrl
          AUTH_LOGIN_FINISH_REDIRECT_URL: !Ref AuthLoginFinishRedirectUrl
          AUTH_LOGOUT_FINISH_REDIRECT_URL: !Ref AuthLogoutFinishRedirectUrl
          SESSION_COOKIE_SECRET: !Ref SessionCookieSecret
    Metadata:
      DockerContext: ./server_nodejs
      Dockerfile: Dockerfile
      DockerTag: v7

  # ANCHOR: Monitoring

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true
