FROM node:18

WORKDIR /home/node/app

COPY package.json package-lock.json tsconfig.json ./
# We will include source file in compose.yaml file as volumes setting.

RUN npm install

CMD ["./node_modules/.bin/nodemon", "-e", "ts"]
